<style>
    shadowing true
    defaultFontName Fira Mono
    TitleFontSize 20
    Padding 5
    dpi 300
    roundcorner 8
    ArrowColor $MOZAIC_WORKS
    BackgroundColor $COLOR_WHITE
    DefaultFontColor $COLOR_TEXT
    ArrowFontColor $COLOR_MUTEDTEXT

    hide circle
    hide empty members
    ClassBackgroundColor $COLOR_WHITE
    ClassAttributeFontColor $COLOR_TEXT
    ClassFontColor $COLOR_WHITE

    ActivityBorderColor $COLOR_BORDER
    ActivityDiamondBorderColor $COLOR_BORDER
    ActorBorderColor $COLOR_BORDER
    AgentBorderColor $COLOR_BORDER
    ArtifactBorderColor $COLOR_BORDER
    CardBorderColor $COLOR_BORDER
    ClassBorderColor $COLOR_BORDER
    CloudBorderColor $COLOR_BORDER
    CollectionsBorderColor $COLOR_BORDER
    ComponentBorderColor $COLOR_BORDER
    ControlBorderColor $COLOR_BORDER
    BoundaryBorderColor $COLOR_BORDER
    DatabaseBorderColor $COLOR_BORDER
    EntityBorderColor $COLOR_BORDER
    FileBorderColor $COLOR_BORDER
    FolderBorderColor $COLOR_BORDER
    FrameBorderColor $COLOR_BORDER
    InterfaceBorderColor $COLOR_BORDER
    LegendBorderColor $COLOR_BORDER
    NodeBorderColor $COLOR_BORDER
    NoteBorderColor $COLOR_BORDER
    ObjectBorderColor $COLOR_BORDER
    PackageBorderColor $COLOR_BORDER
    PageBorderColor $COLOR_BORDER
    ParticipantBorderColor $COLOR_BORDER
    PartitionBorderColor $COLOR_ENDPOINT
    QueueBorderColor $COLOR_BORDER
    RectangleBorderColor $COLOR_BORDER
    SequenceBoxBorderColor $COLOR_BORDER
    SequenceDividerBorderColor $COLOR_BORDER
    SequenceGroupBorderColor $COLOR_BORDER
    SequenceLifeLineBorderColor $COLOR_BORDER
    SequenceReferenceBorderColor $COLOR_BORDER
    StackBorderColor $COLOR_BORDER
    StateBorderColor $COLOR_BORDER
    StereotypeABorderColor $COLOR_BORDER
    StereotypeCBorderColor $COLOR_BORDER
    StereotypeEBorderColor $COLOR_BORDER
    StereotypeIBorderColor $COLOR_BORDER
    StereotypeNBorderColor $COLOR_BORDER
    StorageBorderColor $COLOR_BORDER
    SwimlaneBorderColor $COLOR_BORDER
    UsecaseBorderColor $COLOR_BORDER

    ActivityBackgroundColor $COLOR_FILL
    ActivityDiamondBackgroundColor $COLOR_FILL
    ActorBackgroundColor $COLOR_FILL
    AgentBackgroundColor $COLOR_FILL
    ArtifactBackgroundColor $COLOR_FILL
    BoundaryBackgroundColor $COLOR_FILL
    CardBackgroundColor $COLOR_FILL
    ClassHeaderBackgroundColor $COLOR_FILL
    CloudBackgroundColor $COLOR_FILL
    CollectionsBackgroundColor $COLOR_FILL
    ComponentBackgroundColor $COLOR_FILL
    ControlBackgroundColor $COLOR_FILL
    DatabaseBackgroundColor $COLOR_FILL
    EntityBackgroundColor $COLOR_FILL
    FileBackgroundColor $COLOR_FILL
    FolderBackgroundColor $COLOR_FILL
    FrameBackgroundColor $COLOR_FILL
    IconPackageBackgroundColor $COLOR_FILL
    IconPrivateBackgroundColor $COLOR_FILL
    IconProtectedBackgroundColor $COLOR_FILL
    IconPublicBackgroundColor $COLOR_FILL
    InterfaceBackgroundColor $COLOR_FILL
    LegendBackgroundColor $COLOR_FILL
    NodeBackgroundColor $COLOR_FILL
    NoteBackgroundColor $COLOR_NOTE
    ObjectBackgroundColor $COLOR_FILL
    PackageBackgroundColor $COLOR_FILL
    ParticipantBackgroundColor $COLOR_FILL
    PartitionBackgroundColor $COLOR_FILLCONTAINER
    QueueBackgroundColor $COLOR_FILL
    RectangleBackgroundColor $COLOR_FILL
    SequenceBoxBackgroundColor $COLOR_FILL
    SequenceDividerBackgroundColor $COLOR_FILL
    SequenceGroupBackgroundColor $COLOR_FILL
    SequenceGroupBodyBackgroundColor $COLOR_FILL
    SequenceLifeLineBackgroundColor $COLOR_FILL
    SequenceReferenceBackgroundColor $COLOR_FILL
    SequenceReferenceHeaderBackgroundColor $COLOR_FILL
    StackBackgroundColor $COLOR_FILL
    StateBackgroundColor $COLOR_FILL
    StereotypeABackgroundColor $COLOR_FILL
    StereotypeCBackgroundColor $COLOR_FILL
    StereotypeEBackgroundColor $COLOR_FILL
    StereotypeIBackgroundColor $COLOR_FILL
    StereotypeNBackgroundColor $COLOR_FILL
    StorageBackgroundColor $COLOR_FILL
    TitleBackgroundColor $COLOR_FILL
    UsecaseBackgroundColor $COLOR_FILL

    ActivityStartColor $COLOR_ENDPOINT
    ActivityEndColor $COLOR_ENDPOINT
    StateStartColor $COLOR_ENDPOINT
    StateEndColor $COLOR_ENDPOINT

    TitleBackgroundColor $COLOR_WHITE
    PackageBackgroundColor $COLOR_WHITE
</style>
